#
# Repository validation
#
name: Analyze
on:
- pull_request
jobs:
  analyze:
    name: Analyze repository
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # Run analysis against repository
    - name: Run PSRule analysis
      uses: Microsoft/ps-rule@v2.0.0
      with:
        modules: 'PSRule.Rules.MSFT.OSS'
